#SpringBoot的Debug
#debug: true

server:
  port: 8082

spring:
  #应用名
  application:
    name: weblog-user

  #开发时可以禁用模板缓存
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5

  resources:
    static-locations:
      - classpath:/static/
      - classpath:/templates/

  #jdbc
  datasource:
    username: root
    password: 1109
    url: jdbc:mysql://localhost/weblog?characterEncoding=UTF-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    #指定sql文件位置(如建表sql)，会自动运行sql
    #schema:
      #- classpath:
    # 指定数据池
    type: com.alibaba.druid.pool.DruidDataSource
    #JPA配置
    #jpa:
      #hibernate:
        #ddl-auto: update
        #show-sql: true


  #邮件
  mail:
    host: smtp.qq.com
    username: 1406103364@qq.com
    password: pipaoqoocrnbbagj
    port: 465
    #简单邮件传输协议SMTP
    protocol: smtp
    properties:
      mail.smtp.ssl.enable: true
      mail.smtp.auth: true

#Mybatis配置
mybatis:
  mapper-locations: classpath:com/zh/user/dao/*.xml
#  config-location: classpath:


  #Redis配置
  redis:
    host: localhost

  #RabbitMQService
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
  data:
    mongodb:
      host: localhost
      database: square

    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300


#Eureka,注册成为Eureka的客户端
eureka:
  client:
    #eureka服务端的地址
    service-url:
      defaultZone: http://127.0.0.1:8801/eureka/
  instance:
    #在eureka管理页面可以显示 服务的昵称
    instance-id: weblog-user
    #在eureka管理页面可以显示 服务的IP地址
    prefer-ip-address: true

#Feign,开启熔断器
feign:
  hystrix:
    enabled: true

# slf4j日志配置, 默认info
logging:
  #日志文件file or path(选其一)
  path: /home/micat/log/
  #输出格式: %d指时间，%thread指线程名，%-5level级别从左显示5个宽度，%logger{50}指logger名(限制<50字符) %msg日志消息
#  pattern:
#    console: %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} -%msg%n
#    file: %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} -%msg%n

